const mongoose = require('mongoose');
const Game = require('../models/game_schema');
require('dotenv').config();

mongoose.connect(process.env.DB_ATLAS_URL, {
    useNewUrlParser: true,
    useUnifiedTopology:true
});

const games = [
    {
      "appid": 730,
      "name": "Counter-Strike: Global Offensive",
      "release_year": 2012,
      "developer": "Valve, Hidden Path Entertainment",
      "publisher": "Valve",
      "platforms": "windows, mac, linux",
      "required_age": 0,
      "genres": "Action, Free to Play",
      "categories": "FPS, Multiplayer, Shooter",
      "positive_ratings": 2644404,
      "negative_ratings": 402313,
      "price": 0
    },
    {
      "appid": 2870,
      "name": "X Rebirth",
      "release_year": 2013,
      "developer": "Egosoft",
      "publisher": "Egosoft",
      "platforms": "windows, mac, linux",
      "required_age": 0,
      "genres": "Action, Simulation",
      "categories": "Space, Simulation, Sci-fi",
      "positive_ratings": 2832,
      "negative_ratings": 4032,
      "price": 24.99
    },
    {
      "appid": 7200,
      "name": "Trackmania United Forever Star Edition",
      "release_year": 2008,
      "developer": "Nadeo",
      "publisher": "Ubisoft",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Racing",
      "categories": "Racing, Multiplayer, Level Editor",
      "positive_ratings": 963,
      "negative_ratings": 55,
      "price": 25.99
    },
    {
      "appid": 15370,
      "name": "Heroes of Might & Magic V: Tribes of the East",
      "release_year": 2008,
      "developer": "Nival",
      "publisher": "Ubisoft",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Strategy",
      "categories": "Strategy, Turn-Based Strategy, Turn-Based",
      "positive_ratings": 759,
      "negative_ratings": 66,
      "price": 8.59
    },
    {
      "appid": 17450,
      "name": "Dragon Age: Origins",
      "release_year": 2009,
      "developer": "BioWare",
      "publisher": "Electronic Arts",
      "platforms": "windows",
      "required_age": 0,
      "genres": "RPG",
      "categories": "RPG, Fantasy, Story Rich",
      "positive_ratings": 6207,
      "negative_ratings": 468,
      "price": 14.99
    },
    {
      "appid": 23420,
      "name": "Europa Universalis: Rome - Gold Edition",
      "release_year": 2008,
      "developer": "Paradox Development Studio",
      "publisher": "Paradox Interactive",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Strategy",
      "categories": "Strategy, Grand Strategy, Historical",
      "positive_ratings": 123,
      "negative_ratings": 52,
      "price": 7.99
    },
    {
      "appid": 24200,
      "name": "DC Universe™ Online",
      "release_year": 2011,
      "developer": "Daybreak Game Company",
      "publisher": "Daybreak Game Company",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Action, Adventure, Free to Play, Massively Multiplayer, RPG",
      "categories": "Free to Play, Superhero, Massively Multiplayer",
      "positive_ratings": 10138,
      "negative_ratings": 2654,
      "price": 0
    },
    {
      "appid": 33670,
      "name": "Disciples III - Renaissance Steam Special Edition",
      "release_year": 2010,
      "developer": "Akella, .dat",
      "publisher": "Kalypso Media Digital",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Strategy, RPG",
      "categories": "Strategy, RPG, Turn-Based",
      "positive_ratings": 166,
      "negative_ratings": 134,
      "price": 9.99
    },
    {
      "appid": 39140,
      "name": "FINAL FANTASY VII",
      "release_year": 2013,
      "developer": "Square Enix",
      "publisher": "Square Enix",
      "platforms": "windows",
      "required_age": 12,
      "genres": "RPG",
      "categories": "JRPG, RPG, Classic",
      "positive_ratings": 11722,
      "negative_ratings": 878,
      "price": 9.99
    },
    {
      "appid": 39150,
      "name": "FINAL FANTASY VIII",
      "release_year": 2013,
      "developer": "Square Enix",
      "publisher": "Square Enix",
      "platforms": "windows",
      "required_age": 16,
      "genres": "RPG",
      "categories": "JRPG, RPG, Classic",
      "positive_ratings": 5323,
      "negative_ratings": 682,
      "price": 9.99
    },
    {
      "appid": 39210,
      "name": "FINAL FANTASY XIV Online",
      "release_year": 2014,
      "developer": "Square Enix",
      "publisher": "Square Enix",
      "platforms": "windows",
      "required_age": 16,
      "genres": "Massively Multiplayer, RPG",
      "categories": "MMORPG, Massively Multiplayer, RPG",
      "positive_ratings": 9808,
      "negative_ratings": 2107,
      "price": 9.99
    },
    {
      "appid": 39540,
      "name": "SpellForce - Platinum Edition",
      "release_year": 2009,
      "developer": "Phenomic",
      "publisher": "THQ Nordic",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Action, RPG",
      "categories": "RPG, Strategy, Action",
      "positive_ratings": 694,
      "negative_ratings": 149,
      "price": 8.99
    },
    {
      "appid": 40100,
      "name": "Supreme Commander 2",
      "release_year": 2010,
      "developer": "Gas Powered Games",
      "publisher": "Square Enix",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Strategy",
      "categories": "Strategy, RTS, Sci-fi",
      "positive_ratings": 5336,
      "negative_ratings": 903,
      "price": 8.99
    },
    {
      "appid": 41700,
      "name": "S.T.A.L.K.E.R.: Call of Pripyat",
      "release_year": 2010,
      "developer": "GSC Game World",
      "publisher": "GSC Game World",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Action, RPG",
      "categories": "Open World, Atmospheric, Post-apocalyptic",
      "positive_ratings": 10172,
      "negative_ratings": 470,
      "price": 12.99
    },
    {
      "appid": 42960,
      "name": "Victoria II",
      "release_year": 2010,
      "developer": "Paradox Development Studio",
      "publisher": "Paradox Interactive",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Strategy",
      "categories": "Grand Strategy, Strategy, Historical",
      "positive_ratings": 4743,
      "negative_ratings": 632,
      "price": 14.99
    },
    {
      "appid": 65530,
      "name": "SpellForce 2: Faith in Destiny",
      "release_year": 2012,
      "developer": "Mind Over Matter Studios",
      "publisher": "THQ Nordic",
      "platforms": "windows",
      "required_age": 0,
      "genres": "RPG, Strategy",
      "categories": "Strategy, RPG, RTS",
      "positive_ratings": 125,
      "negative_ratings": 85,
      "price": 13.99
    },
    {
      "appid": 72850,
      "name": "The Elder Scrolls V: Skyrim",
      "release_year": 2011,
      "developer": "Bethesda Game Studios",
      "publisher": "Bethesda Softworks",
      "platforms": "windows",
      "required_age": 16,
      "genres": "RPG",
      "categories": "Open World, RPG, Fantasy",
      "positive_ratings": 237303,
      "negative_ratings": 14951,
      "price": 9.99
    },
    {
      "appid": 107410,
      "name": "Arma 3",
      "release_year": 2013,
      "developer": "Bohemia Interactive",
      "publisher": "Bohemia Interactive",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Action, Simulation, Strategy",
      "categories": "Simulation, Military, Multiplayer",
      "positive_ratings": 105034,
      "negative_ratings": 12524,
      "price": 29.99
    },
    {
      "appid": 204530,
      "name": "Infested Planet",
      "release_year": 2014,
      "developer": "Rocket Bear Games",
      "publisher": "Rocket Bear Games",
      "platforms": "windows, mac",
      "required_age": 0,
      "genres": "Action, Indie, Strategy",
      "categories": "Strategy, Action, Tower Defense",
      "positive_ratings": 1954,
      "negative_ratings": 127,
      "price": 11.39
    },
    {
      "appid": 208500,
      "name": "F1 2012™",
      "release_year": 2012,
      "developer": "Codemasters Birmingham",
      "publisher": "Codemasters",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Racing, Simulation, Sports",
      "categories": "Racing, Simulation, Sports",
      "positive_ratings": 1447,
      "negative_ratings": 176,
      "price": 14.99
    },
    {
      "appid": 218090,
      "name": "Unity of Command: Stalingrad Campaign",
      "release_year": 2012,
      "developer": "2x2 Games",
      "publisher": "2x2 Games",
      "platforms": "windows, mac, linux",
      "required_age": 0,
      "genres": "Indie, Strategy",
      "categories": "Strategy, World War II, Turn-Based Strategy",
      "positive_ratings": 504,
      "negative_ratings": 116,
      "price": 14.99
    },
    {
      "appid": 219340,
      "name": "The Banner Saga: Factions",
      "release_year": 2012,
      "developer": "Stoic",
      "publisher": "Versus Evil",
      "platforms": "windows, mac",
      "required_age": 0,
      "genres": "Free to Play, Indie, RPG, Strategy",
      "categories": "Free to Play, Strategy, RPG",
      "positive_ratings": 569,
      "negative_ratings": 202,
      "price": 0
    },
    {
      "appid": 221020,
      "name": "Towns",
      "release_year": 2012,
      "developer": "Xavi Canal, Ben Palgi",
      "publisher": "SMP",
      "platforms": "windows, mac",
      "required_age": 0,
      "genres": "Indie, RPG, Simulation, Strategy",
      "categories": "City Builder, Indie, Sandbox",
      "positive_ratings": 632,
      "negative_ratings": 1878,
      "price": 9.99
    },
    {
      "appid": 221100,
      "name": "DayZ",
      "release_year": 2018,
      "developer": "Bohemia Interactive",
      "publisher": "Bohemia Interactive",
      "platforms": "windows",
      "required_age": 18,
      "genres": "Action, Adventure, Massively Multiplayer",
      "categories": "Survival, Zombies, Open World",
      "positive_ratings": 118435,
      "negative_ratings": 77169,
      "price": 33.99
    },
    {
      "appid": 221540,
      "name": "DG2: Defense Grid 2",
      "release_year": 2014,
      "developer": "Hidden Path Entertainment",
      "publisher": "505 Games",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Indie, Strategy",
      "categories": "Tower Defense, Strategy, Sci-fi",
      "positive_ratings": 1579,
      "negative_ratings": 354,
      "price": 10.99
    },
    {
      "appid": 221680,
      "name": "Rocksmith® 2014 Edition - Remastered",
      "release_year": 2016,
      "developer": "Ubisoft - San Francisco",
      "publisher": "Ubisoft",
      "platforms": "windows, mac",
      "required_age": 0,
      "genres": "Casual, Simulation",
      "categories": "Music, Education, Simulation",
      "positive_ratings": 8228,
      "negative_ratings": 789,
      "price": 25.99
    },
    {
      "appid": 223750,
      "name": "DCS World Steam Edition",
      "release_year": 2013,
      "developer": "Eagle Dynamics SA",
      "publisher": "The Fighter Collection",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Free to Play, Simulation",
      "categories": "Simulation, Flight, Free to Play",
      "positive_ratings": 5083,
      "negative_ratings": 1534,
      "price": 0
    },
    {
      "appid": 228260,
      "name": "Fallen Enchantress: Legendary Heroes",
      "release_year": 2013,
      "developer": "Stardock Entertainment",
      "publisher": "Stardock Entertainment",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Indie, RPG, Strategy",
      "categories": "Strategy, Fantasy, Turn-Based Strategy",
      "positive_ratings": 1265,
      "negative_ratings": 495,
      "price": 19.49
    },
    {
      "appid": 228760,
      "name": "TrackMania² Canyon",
      "release_year": 2013,
      "developer": "Nadeo",
      "publisher": "Ubisoft",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Racing, Sports",
      "categories": "Racing, Multiplayer, Level Editor",
      "positive_ratings": 1065,
      "negative_ratings": 259,
      "price": 16.99
    },
    {
      "appid": 232910,
      "name": "TrackMania² Stadium",
      "release_year": 2013,
      "developer": "Nadeo",
      "publisher": "Ubisoft",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Racing, Sports",
      "categories": "Racing, Multiplayer, Level Editor",
      "positive_ratings": 2915,
      "negative_ratings": 571,
      "price": 8.59
    },
    {
      "appid": 234670,
      "name": "NARUTO SHIPPUDEN: Ultimate Ninja STORM 3 Full Burst HD",
      "release_year": 2013,
      "developer": "CyberConnect2 Co. Ltd.",
      "publisher": "BANDAI NAMCO Entertainment",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Action, Adventure",
      "categories": "Anime, Fighting, Action",
      "positive_ratings": 8209,
      "negative_ratings": 882,
      "price": 14.99
    },
    {
      "appid": 235620,
      "name": "Small World 2",
      "release_year": 2013,
      "developer": "Days of Wonder",
      "publisher": "Days of Wonder, Asmodee Digital",
      "platforms": "windows, mac, linux",
      "required_age": 0,
      "genres": "Casual, Indie, Strategy",
      "categories": "Board Game, Strategy, Casual",
      "positive_ratings": 520,
      "negative_ratings": 174,
      "price": 6.99
    },
    {
      "appid": 236430,
      "name": "DARK SOULS™ II",
      "release_year": 2014,
      "developer": "FromSoftware, Inc",
      "publisher": "BANDAI NAMCO Entertainment, FromSoftware, Inc",
      "platforms": "windows",
      "required_age": 16,
      "genres": "Action, RPG",
      "categories": "RPG, Dark Fantasy, Difficult",
      "positive_ratings": 30008,
      "negative_ratings": 3799,
      "price": 29.99
    },
    {
      "appid": 236850,
      "name": "Europa Universalis IV",
      "release_year": 2013,
      "developer": "Paradox Development Studio",
      "publisher": "Paradox Interactive",
      "platforms": "windows, mac, linux",
      "required_age": 0,
      "genres": "Simulation, Strategy",
      "categories": "Grand Strategy, Strategy, Historical",
      "positive_ratings": 40346,
      "negative_ratings": 8254,
      "price": 34.99
    },
    {
      "appid": 237950,
      "name": "UFO: Afterlight",
      "release_year": 2014,
      "developer": "Altar Games",
      "publisher": "Bohemia Interactive",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Indie, Strategy",
      "categories": "Strategy, Tactical, Sci-fi",
      "positive_ratings": 210,
      "negative_ratings": 140,
      "price": 4.99
    },
    {
      "appid": 242860,
      "name": "Verdun",
      "release_year": 2015,
      "developer": "M2H, Blackmill Games",
      "publisher": "M2H",
      "platforms": "windows, mac, linux",
      "required_age": 0,
      "genres": "Action, Indie, Strategy",
      "categories": "World War I, FPS, Multiplayer",
      "positive_ratings": 22048,
      "negative_ratings": 4418,
      "price": 15.49
    },
    {
      "appid": 244210,
      "name": "Assetto Corsa",
      "release_year": 2014,
      "developer": "Kunos Simulazioni",
      "publisher": "Kunos Simulazioni",
      "platforms": "windows",
      "required_age": 0,
      "genres": "Indie, Racing, Simulation, Sports",
      "categories": "Racing, Simulation, Driving",
      "positive_ratings": 15277,
      "negative_ratings": 2337,
      "price": 15.49
    },
    {
        "appid": 244450,
        "name": "Men of War: Assault Squad 2",
        "release_year": 2014,
        "developer": "Digitalmindsoft",
        "publisher": "1C Entertainment",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Simulation, Strategy",
        "categories": "Strategy, World War II, War",
        "positive_ratings": 11389,
        "negative_ratings": 2025,
        "price": 19.99
      },
      {
        "appid": 244770,
        "name": "StarMade",
        "release_year": 2014,
        "developer": "Schine, GmbH",
        "publisher": "Schine, GmbH",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Action, Adventure, Indie, RPG, Simulation, Strategy, Early Access",
        "categories": "Early Access, Space, Sandbox",
        "positive_ratings": 1852,
        "negative_ratings": 772,
        "price": 10.99
      },
      {
        "appid": 248390,
        "name": "Craft The World",
        "release_year": 2014,
        "developer": "Dekovir Entertainment",
        "publisher": "Black Maple Games",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Indie, RPG, Simulation, Strategy",
        "categories": "Sandbox, Crafting, Survival",
        "positive_ratings": 6946,
        "negative_ratings": 984,
        "price": 13.99
      },
      {
        "appid": 249130,
        "name": "LEGO® Marvel™ Super Heroes",
        "release_year": 2013,
        "developer": "Traveller's Tales",
        "publisher": "Warner Bros. Interactive Entertainment, Feral Interactive (Mac)",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Action, Adventure",
        "categories": "LEGO, Open World, Superhero",
        "positive_ratings": 8797,
        "negative_ratings": 691,
        "price": 14.99
      },
      {
        "appid": 250900,
        "name": "The Binding of Isaac: Rebirth",
        "release_year": 2014,
        "developer": "Nicalis, Inc.",
        "publisher": "Nicalis, Inc.",
        "platforms": "windows, mac, linux",
        "required_age": 16,
        "genres": "Action",
        "categories": "Indie, Replay Value, Rogue-like",
        "positive_ratings": 72830,
        "negative_ratings": 1840,
        "price": 10.99
      },
      {
        "appid": 251150,
        "name": "The Legend of Heroes: Trails in the Sky",
        "release_year": 2014,
        "developer": "Nihon Falcom",
        "publisher": "XSEED Games, Marvelous USA, Inc.",
        "platforms": "windows",
        "required_age": 0,
        "genres": "RPG",
        "categories": "JRPG, RPG, Anime",
        "positive_ratings": 3413,
        "negative_ratings": 318,
        "price": 12.99
      },
      {
        "appid": 252530,
        "name": "OMSI 2: Steam Edition",
        "release_year": 2013,
        "developer": "MR-Software GbR",
        "publisher": "Aerosoft GmbH",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Casual, Simulation",
        "categories": "Simulation, Driving, Realistic",
        "positive_ratings": 2717,
        "negative_ratings": 803,
        "price": 27.11
      },
      {
        "appid": 252690,
        "name": "Fantasy Grounds",
        "release_year": 2014,
        "developer": "SmiteWorks USA, LLC",
        "publisher": "SmiteWorks USA, LLC",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Indie, RPG, Strategy",
        "categories": "RPG, Strategy, Software",
        "positive_ratings": 377,
        "negative_ratings": 100,
        "price": 29.99
      },
      {
        "appid": 254200,
        "name": "FortressCraft Evolved!",
        "release_year": 2015,
        "developer": "ProjectorGames",
        "publisher": "Digital Tribe",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Adventure, Casual, Indie, RPG, Simulation, Strategy",
        "categories": "Sandbox, Crafting, Building",
        "positive_ratings": 1775,
        "negative_ratings": 622,
        "price": 9.99
      },
      {
        "appid": 257170,
        "name": "Rebuild 3: Gangs of Deadsville",
        "release_year": 2015,
        "developer": "Northway Games, Sarah Northway",
        "publisher": "Northway Games",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Indie, Simulation, Strategy",
        "categories": "Strategy, Zombies, Simulation",
        "positive_ratings": 928,
        "negative_ratings": 163,
        "price": 10.99
      },
      {
        "appid": 259680,
        "name": "Tales of Maj'Eyal",
        "release_year": 2013,
        "developer": "Netcore Games",
        "publisher": "Netcore Games",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Adventure, Indie, RPG",
        "categories": "Rogue-like, RPG, Turn-Based",
        "positive_ratings": 2748,
        "negative_ratings": 133,
        "price": 4.99
      },
      {
        "appid": 269770,
        "name": "Secrets of Grindea",
        "release_year": 2015,
        "developer": "Pixel Ferrets",
        "publisher": "Pixel Ferrets",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Adventure, Indie, RPG, Early Access",
        "categories": "Early Access, RPG, Adventure",
        "positive_ratings": 3642,
        "negative_ratings": 254,
        "price": 10.99
      },
      {
        "appid": 269950,
        "name": "X-Plane 11",
        "release_year": 2017,
        "developer": "Laminar Research",
        "publisher": "Laminar Research",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Simulation",
        "categories": "Simulation, Flight, Realistic",
        "positive_ratings": 2033,
        "negative_ratings": 443,
        "price": 54.99
      },
      {
        "appid": 271590,
        "name": "Grand Theft Auto V",
        "release_year": 2015,
        "developer": "Rockstar North",
        "publisher": "Rockstar Games",
        "platforms": "windows",
        "required_age": 18,
        "genres": "Action, Adventure",
        "categories": "Open World, Action, Multiplayer",
        "positive_ratings": 329061,
        "negative_ratings": 139308,
        "price": 24.99
      },
      {
        "appid": 275530,
        "name": "Z",
        "release_year": 2014,
        "developer": "TickTock Games",
        "publisher": "KISS ltd, Kavcom",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Strategy",
        "categories": "Strategy, Classic, Action",
        "positive_ratings": 605,
        "negative_ratings": 224,
        "price": 4.99
      },
      {
        "appid": 282560,
        "name": "RollerCoaster Tycoon World™",
        "release_year": 2016,
        "developer": "Nvizzio Creations",
        "publisher": "Atari, RCTO Productions",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Simulation, Strategy",
        "categories": "Simulation, Building, Management",
        "positive_ratings": 1182,
        "negative_ratings": 3585,
        "price": 10.99
      },
      {
        "appid": 283880,
        "name": "Heroine's Quest: The Herald of Ragnarok",
        "release_year": 2014,
        "developer": "Crystal Shard",
        "publisher": "Crystal Shard",
        "platforms": "windows, linux",
        "required_age": 0,
        "genres": "Adventure, Free to Play, Indie, RPG",
        "categories": "Adventure, RPG, Point & Click",
        "positive_ratings": 875,
        "negative_ratings": 125,
        "price": 0
      },
      {
        "appid": 284990,
        "name": "Solarix",
        "release_year": 2015,
        "developer": "Pulsetense Games",
        "publisher": "KISS ltd",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Indie",
        "categories": "Action, Stealth, Indie",
        "positive_ratings": 248,
        "negative_ratings": 138,
        "price": 14.99
      },
      {
        "appid": 285920,
        "name": "TerraTech",
        "release_year": 2018,
        "developer": "Payload Studios",
        "publisher": "Payload Studios",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Action, Indie",
        "categories": "Building, Open World, Sandbox",
        "positive_ratings": 4769,
        "negative_ratings": 1022,
        "price": 19.99
      },
      {
        "appid": 287700,
        "name": "METAL GEAR SOLID V: THE PHANTOM PAIN",
        "release_year": 2015,
        "developer": "Konami Digital Entertainment",
        "publisher": "Konami Digital Entertainment",
        "platforms": "windows",
        "required_age": 18,
        "genres": "Action, Adventure",
        "categories": "Stealth, Open World, Story Rich",
        "positive_ratings": 38643,
        "negative_ratings": 4954,
        "price": 24.99
      },
      {
        "appid": 289070,
        "name": "Sid Meier’s Civilization® VI",
        "release_year": 2016,
        "developer": "Firaxis Games, Aspyr (Mac), Aspyr (Linux)",
        "publisher": "2K, Aspyr (Mac), Aspyr (Linux)",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Strategy",
        "categories": "Strategy, Turn-Based Strategy, Historical",
        "positive_ratings": 39127,
        "negative_ratings": 18325,
        "price": 49.99
      },
      {
        "appid": 290080,
        "name": "Life is Feudal: Your Own",
        "release_year": 2015,
        "developer": "Bitbox Ltd.",
        "publisher": "Bitbox Ltd.",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Indie, RPG, Simulation",
        "categories": "Open World, Medieval, Survival",
        "positive_ratings": 6167,
        "negative_ratings": 3395,
        "price": 15.49
      },
      {
        "appid": 291410,
        "name": "Duelyst",
        "release_year": 2016,
        "developer": "Counterplay Games Inc.",
        "publisher": "BANDAI NAMCO Entertainment America",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Free to Play, Indie, Strategy",
        "categories": "Free to Play, Card Game, Strategy",
        "positive_ratings": 3469,
        "negative_ratings": 794,
        "price": 0
      },
      {
        "appid": 292400,
        "name": "Unrest",
        "release_year": 2014,
        "developer": "Pyrodactyl",
        "publisher": "Pyrodactyl",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Adventure, Indie, RPG",
        "categories": "Adventure, Indie, RPG",
        "positive_ratings": 115,
        "negative_ratings": 48,
        "price": 7.19
      },
      {
        "appid": 292730,
        "name": "Call of Duty®: Infinite Warfare",
        "release_year": 2016,
        "developer": "Infinity Ward",
        "publisher": "Activision",
        "platforms": "windows",
        "required_age": 18,
        "genres": "Action, Adventure",
        "categories": "Action, FPS, Multiplayer",
        "positive_ratings": 7821,
        "negative_ratings": 10570,
        "price": 39.99
      },
      {
        "appid": 296490,
        "name": "GemCraft - Chasing Shadows",
        "release_year": 2015,
        "developer": "Game in a Bottle",
        "publisher": "Armor Games Studios",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Indie, Strategy",
        "categories": "Tower Defense, Strategy, Indie",
        "positive_ratings": 2179,
        "negative_ratings": 88,
        "price": 6.99
      },
      {
        "appid": 298180,
        "name": "The Desolate Hope",
        "release_year": 2014,
        "developer": "Scott Cawthon",
        "publisher": "Scott Cawthon",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Adventure, Indie, RPG",
        "categories": "RPG, Free to Play, Adventure",
        "positive_ratings": 752,
        "negative_ratings": 69,
        "price": 0
      },
      {
        "appid": 306130,
        "name": "The Elder Scrolls® Online",
        "release_year": 2017,
        "developer": "Zenimax Online Studios",
        "publisher": "Bethesda Softworks",
        "platforms": "windows, mac",
        "required_age": 18,
        "genres": "Massively Multiplayer, RPG",
        "categories": "RPG, Open World, MMORPG",
        "positive_ratings": 33719,
        "negative_ratings": 11672,
        "price": 14.99
      },
      {
        "appid": 307130,
        "name": "Asteria",
        "release_year": 2014,
        "developer": "Legend Studio",
        "publisher": "Legend Studio",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Adventure, Indie",
        "categories": "Indie, Adventure, Action",
        "positive_ratings": 127,
        "negative_ratings": 97,
        "price": 3.99
      },
      {
        "appid": 311210,
        "name": "Call of Duty®: Black Ops III",
        "release_year": 2015,
        "developer": "Treyarch, Aspyr (Mac)",
        "publisher": "Activision, Aspyr (Mac)",
        "platforms": "windows, mac",
        "required_age": 18,
        "genres": "Action, Adventure",
        "categories": "Multiplayer, FPS, Zombies",
        "positive_ratings": 36255,
        "negative_ratings": 23157,
        "price": 44.99
      },
      {
        "appid": 313160,
        "name": "Farming Simulator 15",
        "release_year": 2014,
        "developer": "Giants Software",
        "publisher": "Giants Software",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Simulation",
        "categories": "Simulation, Multiplayer, Open World",
        "positive_ratings": 10219,
        "negative_ratings": 1066,
        "price": 15.49
      },
      {
        "appid": 318020,
        "name": "Act of Aggression - Reboot Edition",
        "release_year": 2015,
        "developer": "Eugen Systems",
        "publisher": "Focus Home Interactive",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Strategy",
        "categories": "Strategy, RTS, Multiplayer",
        "positive_ratings": 1329,
        "negative_ratings": 836,
        "price": 23.99
      },
      {
        "appid": 320320,
        "name": "Darkstone",
        "release_year": 2014,
        "developer": "Delphine Software",
        "publisher": "Microids",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, RPG",
        "categories": "RPG, Action, Hack and Slash",
        "positive_ratings": 160,
        "negative_ratings": 56,
        "price": 3.99
      },
      {
        "appid": 323470,
        "name": "DRAGON BALL XENOVERSE",
        "release_year": 2015,
        "developer": "DIMPS",
        "publisher": "BANDAI NAMCO Entertainment",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action",
        "categories": "Anime, Fighting, Action",
        "positive_ratings": 12601,
        "negative_ratings": 1680,
        "price": 31.99
      },
      {
        "appid": 324510,
        "name": "Boundless",
        "release_year": 2018,
        "developer": "Wonderstruck",
        "publisher": "Square Enix",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Action, Adventure, Indie, Massively Multiplayer, RPG",
        "categories": "Sandbox, Massively Multiplayer, Open World",
        "positive_ratings": 1153,
        "negative_ratings": 486,
        "price": 32.99
      },
      {
        "appid": 325610,
        "name": "Total War: ATTILA",
        "release_year": 2015,
        "developer": "CREATIVE ASSEMBLY",
        "publisher": "SEGA",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Strategy",
        "categories": "Strategy, Historical, War",
        "positive_ratings": 12297,
        "negative_ratings": 4469,
        "price": 29.99
      },
      {
        "appid": 326160,
        "name": "Shroud of the Avatar: Forsaken Virtues",
        "release_year": 2018,
        "developer": "Portalarium",
        "publisher": "Portalarium",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Free to Play, Massively Multiplayer, RPG",
        "categories": "RPG, Massively Multiplayer, Free to Play",
        "positive_ratings": 1065,
        "negative_ratings": 1017,
        "price": 0
      },
      {
        "appid": 326670,
        "name": "Warhammer Quest",
        "release_year": 2015,
        "developer": "Rodeo Games, Twistplay",
        "publisher": "Chilled Mouse",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "RPG, Strategy",
        "categories": "RPG, Strategy, Turn-Based",
        "positive_ratings": 516,
        "negative_ratings": 246,
        "price": 10.99
      },
      {
        "appid": 333950,
        "name": "Medieval Engineers",
        "release_year": 2015,
        "developer": "Keen Software House",
        "publisher": "Keen Software House",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Indie, Simulation, Strategy, Early Access",
        "categories": "Early Access, Building, Medieval",
        "positive_ratings": 3233,
        "negative_ratings": 1376,
        "price": 12.99
      },
      {
        "appid": 335300,
        "name": "DARK SOULS™ II: Scholar of the First Sin",
        "release_year": 2015,
        "developer": "FromSoftware, Inc",
        "publisher": "BANDAI NAMCO Entertainment, FromSoftware, Inc",
        "platforms": "windows",
        "required_age": 16,
        "genres": "Action, RPG",
        "categories": "RPG, Dark Fantasy, Difficult",
        "positive_ratings": 25959,
        "negative_ratings": 4289,
        "price": 29.99
      },
      {
        "appid": 335820,
        "name": "Dream Of Mirror Online",
        "release_year": 2015,
        "developer": "SoftStar",
        "publisher": "SubaGames",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Adventure, Free to Play, Massively Multiplayer, RPG",
        "categories": "Free to Play, Massively Multiplayer, Anime",
        "positive_ratings": 242,
        "negative_ratings": 211,
        "price": 0
      },
      {
        "appid": 339600,
        "name": "VEGA Conflict",
        "release_year": 2015,
        "developer": "KIXEYE",
        "publisher": "KIXEYE",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Free to Play, Massively Multiplayer, Strategy",
        "categories": "Free to Play, Space, Strategy",
        "positive_ratings": 1471,
        "negative_ratings": 1322,
        "price": 0
      },
      {
        "appid": 341390,
        "name": "Vulture for NetHack",
        "release_year": 2015,
        "developer": "DarkArts Studios",
        "publisher": "DarkArts Studios",
        "platforms": "windows, linux",
        "required_age": 0,
        "genres": "Indie, RPG, Strategy",
        "categories": "RPG, Rogue-like, Procedural Generation",
        "positive_ratings": 102,
        "negative_ratings": 45,
        "price": 2.09
      },
      {
        "appid": 344760,
        "name": "Reign Of Kings",
        "release_year": 2015,
        "developer": "Code}{atch",
        "publisher": "Code}{atch",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Adventure, Indie, RPG, Simulation",
        "categories": "Survival, Open World, Medieval",
        "positive_ratings": 8076,
        "negative_ratings": 5997,
        "price": 7.19
      },
      {
        "appid": 345350,
        "name": "LIGHTNING RETURNS™: FINAL FANTASY® XIII",
        "release_year": 2015,
        "developer": "Square Enix",
        "publisher": "Square Enix",
        "platforms": "windows",
        "required_age": 16,
        "genres": "RPG",
        "categories": "RPG, JRPG, Female Protagonist",
        "positive_ratings": 2135,
        "negative_ratings": 527,
        "price": 12.99
      },
      {
        "appid": 345610,
        "name": "The Fruit of Grisaia",
        "release_year": 2015,
        "developer": "Frontwing",
        "publisher": "Frontwing USA",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Adventure, Casual",
        "categories": "Visual Novel, Anime, Nudity",
        "positive_ratings": 692,
        "negative_ratings": 37,
        "price": 29.99
      },
      {
        "appid": 359320,
        "name": "Elite Dangerous",
        "release_year": 2015,
        "developer": "Frontier Developments",
        "publisher": "Frontier Developments",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Adventure, Massively Multiplayer, RPG, Simulation, Strategy",
        "categories": "Space Sim, Space, Open World",
        "positive_ratings": 26143,
        "negative_ratings": 11006,
        "price": 19.99
      },
      {
        "appid": 359550,
        "name": "Tom Clancy's Rainbow Six® Siege",
        "release_year": 2015,
        "developer": "Ubisoft Montreal",
        "publisher": "Ubisoft",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action",
        "categories": "FPS, Multiplayer, Tactical",
        "positive_ratings": 251178,
        "negative_ratings": 59620,
        "price": 16.99
      },
      {
        "appid": 361800,
        "name": "Tree of Life",
        "release_year": 2017,
        "developer": "oddonegames",
        "publisher": "oddonegames",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Indie, Massively Multiplayer, RPG",
        "categories": "Survival, Sandbox, Open World",
        "positive_ratings": 4433,
        "negative_ratings": 2203,
        "price": 14.99
      },
      {
        "appid": 364360,
        "name": "Total War: WARHAMMER",
        "release_year": 2016,
        "developer": "CREATIVE ASSEMBLY, Feral Interactive (Linux), Feral Interactive (Mac)",
        "publisher": "SEGA, Feral Interactive (Linux), Feral Interactive (Mac)",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Action, Strategy",
        "categories": "Strategy, Fantasy, War",
        "positive_ratings": 29826,
        "negative_ratings": 9878,
        "price": 39.99
      },
      {
        "appid": 374280,
        "name": "Hired Ops",
        "release_year": 2016,
        "developer": "Absolut Soft LLC",
        "publisher": "Absolut Soft LLC",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Early Access",
        "categories": "Early Access, Action, FPS",
        "positive_ratings": 1201,
        "negative_ratings": 1001,
        "price": 6.99
      },
      {
        "appid": 375900,
        "name": "Trackmania® Turbo",
        "release_year": 2016,
        "developer": "Nadeo",
        "publisher": "Ubisoft",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Massively Multiplayer, Racing",
        "categories": "Racing, Level Editor, Arcade",
        "positive_ratings": 742,
        "negative_ratings": 441,
        "price": 33.99
      },
      {
        "appid": 375910,
        "name": "Anno 2205™",
        "release_year": 2015,
        "developer": "Blue Byte",
        "publisher": "Ubisoft",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Simulation, Strategy",
        "categories": "Strategy, City Builder, Simulation",
        "positive_ratings": 2141,
        "negative_ratings": 1245,
        "price": 33.99
      },
      {
        "appid": 376210,
        "name": "The Isle",
        "release_year": 2015,
        "developer": "Afterthought LLC",
        "publisher": "Afterthought LLC",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Adventure, Indie, Massively Multiplayer, Simulation, Early Access",
        "categories": "Early Access, Dinosaurs, Survival",
        "positive_ratings": 7107,
        "negative_ratings": 3219,
        "price": 14.99
      },
      {
        "appid": 377160,
        "name": "Fallout 4",
        "release_year": 2015,
        "developer": "Bethesda Game Studios",
        "publisher": "Bethesda Softworks",
        "platforms": "windows",
        "required_age": 18,
        "genres": "RPG",
        "categories": "Open World, Post-apocalyptic, Exploration",
        "positive_ratings": 110376,
        "negative_ratings": 45377,
        "price": 19.99
      },
      {
        "appid": 377530,
        "name": "侠客风云传(Tale of Wuxia)",
        "release_year": 2016,
        "developer": "Heluo Studio",
        "publisher": "FHYX（凤凰游戏）",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Adventure, Casual, RPG, Simulation, Strategy",
        "categories": "RPG, Martial Arts, Strategy",
        "positive_ratings": 2280,
        "negative_ratings": 588,
        "price": 12.99
      },
      {
        "appid": 377840,
        "name": "FINAL FANTASY IX",
        "release_year": 2016,
        "developer": "Square Enix",
        "publisher": "Square Enix",
        "platforms": "windows",
        "required_age": 12,
        "genres": "RPG",
        "categories": "JRPG, Great Soundtrack, Story Rich",
        "positive_ratings": 3875,
        "negative_ratings": 325,
        "price": 15.99
      },
      {
        "appid": 380140,
        "name": "The Secret of Tremendous Corporation",
        "release_year": 2015,
        "developer": "Sebastian Krzyszkowiak, Konrad Burandt, Paweł Radej",
        "publisher": "dosowisko.net",
        "platforms": "windows, linux",
        "required_age": 0,
        "genres": "Adventure, Casual, Free to Play, Indie",
        "categories": "Free to Play, Adventure, Indie",
        "positive_ratings": 218,
        "negative_ratings": 50,
        "price": 0
      },
      {
        "appid": 380360,
        "name": "Tap Tap Infinity",
        "release_year": 2015,
        "developer": "Scary Bee LLC",
        "publisher": "Scary Bee LLC",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Action, Casual, Free to Play, Indie, RPG",
        "categories": "Clicker, Free to Play, Casual",
        "positive_ratings": 632,
        "negative_ratings": 219,
        "price": 0
      },
      {
        "appid": 382310,
        "name": "Eco",
        "release_year": 2018,
        "developer": "Strange Loop Games",
        "publisher": "Strange Loop Games",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Indie, Simulation, Early Access",
        "categories": "Early Access, Survival, Open World",
        "positive_ratings": 1875,
        "negative_ratings": 639,
        "price": 23.79
      },
      {
        "appid": 384300,
        "name": "CPUCores :: Maximize Your FPS",
        "release_year": 2015,
        "developer": "StartupTim, LLC, Tim Sullivan",
        "publisher": "StartupTim, LLC, Tim Sullivan",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Utilities",
        "categories": "Utilities, Software, Singleplayer",
        "positive_ratings": 6208,
        "negative_ratings": 2324,
        "price": 10.99
      },
      {
        "appid": 385760,
        "name": "NBA 2K17",
        "release_year": 2016,
        "developer": "Visual Concepts",
        "publisher": "2K",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Sports",
        "categories": "Basketball, Sports, Multiplayer",
        "positive_ratings": 4353,
        "negative_ratings": 3893,
        "price": 39.99
      },
      {
        "appid": 389730,
        "name": "TEKKEN 7",
        "release_year": 2017,
        "developer": "BANDAI NAMCO Studios Inc.",
        "publisher": "BANDAI NAMCO Entertainment",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Sports",
        "categories": "Fighting, Action, Multiplayer",
        "positive_ratings": 15372,
        "negative_ratings": 3135,
        "price": 34.99
      },
      {
        "appid": 393420,
        "name": "Hurtworld",
        "release_year": 2015,
        "developer": "Bankroll Studios",
        "publisher": "Bankroll Studios",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Action, Adventure, Simulation, Early Access",
        "categories": "Early Access, Survival, Open World",
        "positive_ratings": 15574,
        "negative_ratings": 5362,
        "price": 19.49
      },
      {
        "appid": 394360,
        "name": "Hearts of Iron IV",
        "release_year": 2016,
        "developer": "Paradox Development Studio",
        "publisher": "Paradox Interactive",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Simulation, Strategy",
        "categories": "Strategy, World War II, Grand Strategy",
        "positive_ratings": 34711,
        "negative_ratings": 5251,
        "price": 34.99
      },
      {
        "appid": 398810,
        "name": "openCanvas 7",
        "release_year": 2017,
        "developer": "PGN Inc",
        "publisher": "PGN Inc",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Design & Illustration, Photo Editing",
        "categories": "Design & Illustration, Photo Editing",
        "positive_ratings": 141,
        "negative_ratings": 38,
        "price": 45
      },
      {
        "appid": 400910,
        "name": "Rabi-Ribi",
        "release_year": 2016,
        "developer": "CreSpirit, GemaYue",
        "publisher": "Sekai Project",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Adventure, Casual, Indie",
        "categories": "Anime, Cute, Bullet Hell",
        "positive_ratings": 6496,
        "negative_ratings": 167,
        "price": 13.59
      },
      {
        "appid": 406730,
        "name": "1,000 Heads Among the Trees",
        "release_year": 2015,
        "developer": "Aaron Oldenburg",
        "publisher": "KISS ltd",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Indie",
        "categories": "Indie, Horror, Adventure",
        "positive_ratings": 46,
        "negative_ratings": 37,
        "price": 4.99
      },
      {
        "appid": 410380,
        "name": "HEX: Shards of Fate",
        "release_year": 2016,
        "developer": "Hex Entertainment",
        "publisher": "Hex Entertainment",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Adventure, Free to Play, RPG, Strategy",
        "categories": "Trading Card Game, Free to Play, Card Game",
        "positive_ratings": 1055,
        "negative_ratings": 580,
        "price": 0
      },
      {
        "appid": 412830,
        "name": "STEINS;GATE",
        "release_year": 2016,
        "developer": "MAGES. Inc.",
        "publisher": "Spike Chunsoft Co., Ltd.",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Adventure",
        "categories": "Visual Novel, Anime, Story Rich",
        "positive_ratings": 5720,
        "negative_ratings": 130,
        "price": 23.99
      },
      {
        "appid": 415200,
        "name": "Motorsport Manager",
        "release_year": 2016,
        "developer": "Playsport Games",
        "publisher": "SEGA",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Racing, Simulation, Sports, Strategy",
        "categories": "Management, Racing, Simulation",
        "positive_ratings": 4278,
        "negative_ratings": 488,
        "price": 24.99
      },
      {
        "appid": 418150,
        "name": "The Madness of Little Emma",
        "release_year": 2015,
        "developer": "Bartosz Bojarowski",
        "publisher": "Bartosz Bojarowski",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Action, Indie",
        "categories": "Indie, Action, Platformer",
        "positive_ratings": 107,
        "negative_ratings": 24,
        "price": 5.99
      },
      {
        "appid": 424370,
        "name": "Wolcen: Lords of Mayhem",
        "release_year": 2016,
        "developer": "WOLCEN Studio",
        "publisher": "WOLCEN Studio",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Adventure, Indie, RPG, Early Access",
        "categories": "Early Access, Hack and Slash, RPG",
        "positive_ratings": 2787,
        "negative_ratings": 1306,
        "price": 27.99
      },
      {
        "appid": 427520,
        "name": "Factorio",
        "release_year": 2016,
        "developer": "Wube Software LTD.",
        "publisher": "Wube Software LTD.",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Casual, Indie, Simulation, Strategy, Early Access",
        "categories": "Early Access, Base-Building, Resource Management",
        "positive_ratings": 47918,
        "negative_ratings": 723,
        "price": 21
      },
      {
        "appid": 429660,
        "name": "Tales of Berseria™",
        "release_year": 2017,
        "developer": "BANDAI NAMCO Studios Inc.",
        "publisher": "BANDAI NAMCO Entertainment",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, RPG",
        "categories": "Anime, JRPG, RPG",
        "positive_ratings": 7427,
        "negative_ratings": 536,
        "price": 39.99
      },
      {
        "appid": 434030,
        "name": "Aerofly FS 2 Flight Simulator",
        "release_year": 2017,
        "developer": "IPACS",
        "publisher": "IPACS",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Indie, Simulation",
        "categories": "Simulation, Flight, Realistic",
        "positive_ratings": 787,
        "negative_ratings": 280,
        "price": 44.99
      },
      {
        "appid": 436150,
        "name": "Governor of Poker 3",
        "release_year": 2016,
        "developer": "Azerion, YoudaGames",
        "publisher": "Azerion, Youda Games Holding B.V.",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Casual, Free to Play, Massively Multiplayer, Simulation",
        "categories": "Free to Play, Card Game, Massively Multiplayer",
        "positive_ratings": 2163,
        "negative_ratings": 866,
        "price": 0
      },
      {
        "appid": 438740,
        "name": "Friday the 13th: The Game",
        "release_year": 2017,
        "developer": "IllFonic",
        "publisher": "Gun Media",
        "platforms": "windows",
        "required_age": 18,
        "genres": "Action",
        "categories": "Horror, Multiplayer, Survival Horror",
        "positive_ratings": 19663,
        "negative_ratings": 8304,
        "price": 15.49
      },
      {
        "appid": 440900,
        "name": "Conan Exiles",
        "release_year": 2018,
        "developer": "Funcom",
        "publisher": "Funcom",
        "platforms": "windows",
        "required_age": 18,
        "genres": "Action, Adventure, Massively Multiplayer, RPG, Simulation, Strategy",
        "categories": "Survival, Open World, Crafting",
        "positive_ratings": 22001,
        "negative_ratings": 9594,
        "price": 33.99
      },
      {
        "appid": 445220,
        "name": "Avorion",
        "release_year": 2017,
        "developer": "Boxelware",
        "publisher": "Boxelware",
        "platforms": "windows, linux",
        "required_age": 0,
        "genres": "Action, Indie, Simulation, Early Access",
        "categories": "Early Access, Space, Sandbox",
        "positive_ratings": 3190,
        "negative_ratings": 398,
        "price": 13.59
      },
      {
        "appid": 447020,
        "name": "Farming Simulator 17",
        "release_year": 2016,
        "developer": "Giants Software",
        "publisher": "Focus Home Interactive",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Simulation",
        "categories": "Simulation, Multiplayer, Agriculture",
        "positive_ratings": 11211,
        "negative_ratings": 1025,
        "price": 15.99
      },
      {
        "appid": 447820,
        "name": "Day of Infamy",
        "release_year": 2017,
        "developer": "New World Interactive",
        "publisher": "New World Interactive",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Action, Indie, Strategy",
        "categories": "World War II, FPS, Multiplayer",
        "positive_ratings": 14349,
        "negative_ratings": 3169,
        "price": 11.39
      },
      {
        "appid": 449800,
        "name": "Attack on Titan / A.O.T. Wings of Freedom",
        "release_year": 2016,
        "developer": "KOEI TECMO GAMES CO., LTD.",
        "publisher": "KOEI TECMO GAMES CO., LTD.",
        "platforms": "windows",
        "required_age": 18,
        "genres": "Action",
        "categories": "Anime, Action, Gore",
        "positive_ratings": 2501,
        "negative_ratings": 479,
        "price": 49.99
      },
      {
        "appid": 454650,
        "name": "DRAGON BALL XENOVERSE 2",
        "release_year": 2016,
        "developer": "QLOC, DIMPS",
        "publisher": "BANDAI NAMCO Entertainment",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Action, Adventure, Casual, Massively Multiplayer",
        "categories": "Anime, Fighting, Action",
        "positive_ratings": 9531,
        "negative_ratings": 2495,
        "price": 39.99
      },
      {
        "appid": 457590,
        "name": "Luna Online: Reborn",
        "release_year": 2017,
        "developer": "Funtime",
        "publisher": "Subagames",
        "platforms": "windows",
        "required_age": 0,
        "genres": "Adventure, Casual, Free to Play, Massively Multiplayer, RPG",
        "categories": "RPG, Massively Multiplayer, Free to Play",
        "positive_ratings": 153,
        "negative_ratings": 125,
        "price": 0
      },
      {
        "appid": 459820,
        "name": "Crush Crush",
        "release_year": 2016,
        "developer": "Sad Panda Studios",
        "publisher": "Sad Panda Studios",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Casual, Free to Play, Indie",
        "categories": "Free to Play, Sexual Content, Nudity",
        "positive_ratings": 7239,
        "negative_ratings": 982,
        "price": 0
      },
      {
        "appid": 461560,
        "name": "MANDAGON",
        "release_year": 2016,
        "developer": "Blind Sky Studios",
        "publisher": "Blind Sky Studios",
        "platforms": "windows, mac",
        "required_age": 0,
        "genres": "Adventure, Free to Play, Indie",
        "categories": "Free to Play, Pixel Graphics, Adventure",
        "positive_ratings": 4600,
        "negative_ratings": 249,
        "price": 0
      },
      {
        "appid": 462960,
        "name": "Caveman World: Mountains of Unga Boonga",
        "release_year": 2016,
        "developer": "GrabTheGames Studios",
        "publisher": "GrabTheGames",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Adventure, Casual, Indie",
        "categories": "Casual, Indie, Adventure",
        "positive_ratings": 330,
        "negative_ratings": 170,
        "price": 1.59
      },
      {
        "appid": 464350,
        "name": "Screeps",
        "release_year": 2016,
        "developer": "Screeps",
        "publisher": "Screeps",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Indie, Massively Multiplayer, Strategy",
        "categories": "Programming, Strategy, Massively Multiplayer",
        "positive_ratings": 736,
        "negative_ratings": 97,
        "price": 10.99
      },
      {
        "appid": 464920,
        "name": "Surviving Mars",
        "release_year": 2018,
        "developer": "Haemimont Games",
        "publisher": "Paradox Interactive",
        "platforms": "windows, mac, linux",
        "required_age": 0,
        "genres": "Simulation, Strategy",
        "categories": "Strategy, City Builder, Survival",
        "positive_ratings": 3942,
        "negative_ratings": 1608,
        "price": 26.99
      }

  ];

 const seedDB = async () => {
    await Game.deleteMany({});
    console.log("Games Deleted");
    await Game.insertMany(games);
    console.log("New games inserted");
}

seedDB().then(() => {
    mongoose.connection.close
    console.log("Database seeded!");
});